# fly.toml app configuration file generated for flywunder on 2024-05-15T16:13:22+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'flywunder'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 9991
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = ''
  internal_port = 9991
  ports = []

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
